<?php
$paypal_currency["AUD"]="AUD";
$paypal_currency["BRL"]="BRL";
$paypal_currency["GBP"]="GBP";
$paypal_currency["CAD"]="CAD";
$paypal_currency["CZK"]="CZK";
$paypal_currency["DKK"]="DKK";
$paypal_currency["EUR"]="EUR";
$paypal_currency["HKD"]="HKD";
$paypal_currency["HUF"]="HUF";
$paypal_currency["ILS"]="ILS";
$paypal_currency["JPY"]="JPY";
$paypal_currency["MXN"]="MXN";
$paypal_currency["TWD"]="TWD";
$paypal_currency["NZD"]="NZD";
$paypal_currency["NOK"]="NOK";
$paypal_currency["PHP"]="PHP";
$paypal_currency["PLN"]="PLN";
$paypal_currency["SGD"]="SGD";
$paypal_currency["SEK"]="SEK";
$paypal_currency["CHF"]="CHF";
$paypal_currency["THB"]="THB";
$paypal_currency["USD"]="USD";
?>